language: python
python:
  - "2.7"
  - "3.6" # current default Python on Travis CI
  - "3.7"
install:
  - pip install codecov
  - pip install pycryptodome
script:
  - coverage run -m unittest discover
after_success:
  - codecov
