language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install pycryptodome
# command to run tests
script:
  - python -m unittest
